export const courses = [
    "Doctor of Philosophy In Business Management",
    "Doctor of Philosophy in Finance Program",
    "Doctor of Philosophy in Information Systems",
    "Master of Arts Counselling Psychology",
    "Master of Business Administration (MBA)",
    "Master of Business Administration Corporate Management",
    "Master of Business Administration Human Resource Management",
    "Master of Business Administration Marketing",
    "Master of Business Administration Procurement and Supplies Management",
    "Master of Education (M.Ed)",
    "Master of Education Leadership and Management",
    "Master of Educational Administration, Curriculum and Policy Studies",
    "Master of Science in Commerce",
    "Master of Science in Data Analytics",
    "Master of Science In Data Science",
    "Master of Science in Development Finance",
    "Master of Science in Information Systems Management",
    "Master of Science in Supply Chain Management",
    "Master of Science Knowledge Management and Innovation",
    "Bachelor of Arts Counselling Psychology",
    "Bachelor of Arts in Criminology",
    "Bachelor of Arts in Economics and Business Studies",
    "Bachelor of Arts in Film Technology and Performing Arts",
    "Bachelor of Arts in Journalism and Digital Media",
    "Bachelor of Business Information Technology",
    "Bachelor of Commerce",
    "Bachelor of Education Arts",
    "Bachelor of Education Early Childhood Education",
    "Bachelor of International Business Management",
    "Bachelor of Procurement and Logistics",
    "Bachelor of Public Management",
    "Bachelor of Science in Actuarial Science",
    "Bachelor of Science in Applied Computing",
    "Bachelor of Science In Data Science",
    "Bachelor of Science in Economics & Statistics",
    "Bachelor of Science in Forensic Accounting",
    "Bachelor of Science in Gaming and Animation Technology",
    "Bachelor of Science in Information and Communications Technology",
    "Bachelor of Science in Information Security and Forensics",
    "Bachelor of Science in Information Technology",
    "Bachelor of Science in Software Development",
    "Post Graduate Diploma in Education",
    "Accounting Technicians Diploma (ATD)",
    "Advanced Excel",
    "Association of Chartered Certified Accountants (ACCA- UK)",
    "AWS � Cloud Practitioner",
    "Backend Web Development With Python",
    "Certificate in Accounting and Management Skills (CAMS)",
    "Certified Forensic Fraud Examiner (CFFE)",
    "Certified Human Resource Professional (CHRP)",
    "Certified Information System Auditor (CISA)",
    "Certified Information Systems Solutions Expert (CISSE)",
    "Certified Investment and Financial Analysts (CIFA)",
    "Certified Procurement and Supply Professional (CPSP-K)",
    "Certified Public Accountants (CPA)",
    "Certified Secretaries (CS)",
    "Data Analytics With Python",
    "International English Language Testing System (IELTS)",
    "Quickbooks Accounting",
    "Sage Accounting",
    "Certificate in Banking",
    "Certificate in Business Information Technology",
    "Certificate in Business Management",
    "Certificate in Counselling Psychology",
    "Certificate in Film Technology",
    "Certificate in Information technology",
    "Certificate in Procurement and Logisitics",
    "Certificate in Project Management",
    "Diploma Criminology and Criminal Justice Programme Structure",
    "Diploma in Banking",
    "Diploma in Business Information Technology",
    "Diploma in Business Management",
    "Diploma in Computer Networks and Systems Administration",
    "Diploma in Counselling Psychology",
    "Diploma in Data Management and Analytics (DDMA)",
    "Diploma in Education",
    "Diploma in Film Technology",
    "Diploma In Human Resource Management (DHRM)",
    "Diploma in Information Technology",
    "Diploma in Journalism and Digital Media",
    "Diploma in Pedagogy and Instruction",
    "Diploma in Procurement and Logistics",
    "Diploma in Project Management",
    "Diploma in Public Management",
    "Accounting Packages",
    "CCNA ( Level 1-3 )",
    "Certificate in Computer Applications",
    "International Certificate of Digital Literacy (ICDL)",
    "Linux (Level 1-3)",
    "Microsoft Office",
    "Statistical Package for Social Sciences (SPSS)",
    "Web Applications and Development",
    "Artisan Certificate in Food and Beverages",
    "Craft Certificate in Business Management",
    "Craft Certificate in Food and Bevarages",
    "Craft Certificate in Human Resource Management",
    "Craft Certificate in Information Communication Technology (ICT)",
    "Diploma in Food and  Beverages",
    "Diploma in Information Communication Technology",
]
