export const interests = [
  "Tech & Coding",
  "Engineering",
  "Medicine",
  "Business",
  "Law",
  "Education",
  "Agriculture",
  "Math & Stats",
  "Football",
  "Basketball",
  "Running",
  "Volleyball",
  "Swimming",
  "Rugby",
  "Tennis",
  "Gym & Fitness",
  "Music",
  "Art & Design",
  "Photography",
  "Dance",
  "Theatre",
  "Poetry",
  "Writing",
  "Fashion",
  "Hiking",
  "Gaming",
  "Reading",
  "Cooking",
  "Travel",
  "Wellness",
  "Meditation",
  "Content Creation",
  "Leadership",
  "Volunteering",
  "Entrepreneurship",
  "Environment",
  "Debate",
  "Chess",
  "Startups",
  "Innovation"
];
