name: Deploy Dev Branch to Vercel

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies (Clean Install)
        run: npm ci

      - name: ESLint Fix
        run: npx eslint --fix src

      - name: Lint with ESLint
        run: npx eslint src

      - name: Build and Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
        run: |
          npx vercel --prod --token=$VERCEL_TOKEN
