name: Nightly Dev to Main Merge

on:
  schedule:
    # Runs at midnight UTC (00:00)
    - cron: '0 0 * * *'

jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest
    
    # Add permission configuration
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use PAT instead of GITHUB_TOKEN
          token: ${{ secrets.NIGHTLY_MERGE_PAT }}
          
      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
          
      - name: Merge dev into main
        run: |
          # Switch to main branch
          git checkout main
          
          # Pull latest changes from both branches
          git pull origin main
          git pull origin dev
          
          # Merge dev into main
          git merge --no-ff origin/dev -m "Automated merge of dev into main"
          
          # Push changes
          git push origin main
        env:
          # Use PAT instead of GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_MERGE_PAT }}

      - name: Handle merge failure
        if: failure()
        run: |
          echo "Merge failed. Creating pull request instead..."
          
          # Create a new branch for the merge
          timestamp=$(date +%Y%m%d_%H%M%S)
          branch_name="automated-merge-$timestamp"
          git checkout -b $branch_name
          
          # Try to merge (this may fail, but we'll capture the state)
          git merge origin/dev || true
          git push origin $branch_name
          
          # Create pull request using GitHub CLI
          gh pr create \
            --base main \
            --head $branch_name \
            --title "Automated merge of dev into main ($timestamp)" \
            --body "Automated merge attempt failed. Please resolve conflicts manually."
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_MERGE_PAT }}
